import Foundation
import Contacts

struct ContactSyncPayload {
    let profileId: UUID
    let name: String
    let phoneNumber: String?
    let email: String?

    let eventId: UUID
    let eventName: String
    let eventDate: Date

    let interactionSummary: String

    // Preserve EL intelligence
    let signalScore: Double
    let interactionCount: Int
    let intentAlignment: Double
}

final class ContactSyncService {
    static let shared = ContactSyncService()

    private let defaults = UserDefaults.standard
    private let idempotencyPrefix = "contactsync.processed"
    private var permissionCache: Bool?
    private var didRequestPermission = false
    private var inFlightKeys = Set<String>()
    private let lock = NSLock()

    private init() {}

    // MARK: - Permission

    func requestAccessIfNeeded() async -> Bool {
        lock.lock()
        if let cached = permissionCache {
            lock.unlock()
            return cached
        }
        if didRequestPermission {
            lock.unlock()
            return false
        }
        didRequestPermission = true
        lock.unlock()

        let store = CNContactStore()
        let granted: Bool

        switch CNContactStore.authorizationStatus(for: .contacts) {
        case .authorized:
            granted = true
        case .denied, .restricted:
            granted = false
        case .notDetermined:
            granted = (try? await store.requestAccess(for: .contacts)) ?? false
        @unknown default:
            granted = false
        }

        lock.lock()
        permissionCache = granted
        lock.unlock()
        return granted
    }

    // MARK: - Idempotency

    func shouldCreateContact(profileId: UUID, eventId: UUID) -> Bool {
        let key = "\(profileId.uuidString.lowercased())_\(eventId.uuidString.lowercased())"
        let persistedKey = "\(idempotencyPrefix).\(key)"

        lock.lock()
        defer { lock.unlock() }

        if inFlightKeys.contains(key) {
            return false
        }

        if defaults.bool(forKey: persistedKey) {
            return false
        }

        inFlightKeys.insert(key)
        return true
    }

    // MARK: - Note Builder

    func buildNote(from payload: ContactSyncPayload) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale.current
        formatter.dateFormat = "LLLL yyyy"

        let signalLabel: String
        if payload.signalScore >= 1.5 {
            signalLabel = "Strong"
        } else if payload.signalScore >= 0.5 {
            signalLabel = "Moderate"
        } else {
            signalLabel = "Light"
        }

        let context = payload.interactionSummary.trimmingCharacters(in: .whitespacesAndNewlines)

        return """
        Met at \(payload.eventName) — \(formatter.string(from: payload.eventDate))

        Context:
        \(context.isEmpty ? "Meaningful interaction" : context)

        Signal:
        \(signalLabel) interaction signal

        Generated by Nearify
        """
    }

    // MARK: - Write

    @discardableResult
    func createOrUpdateContact(payload: ContactSyncPayload) async -> Bool {
        let dedupeKey = "\(payload.profileId.uuidString.lowercased())_\(payload.eventId.uuidString.lowercased())"
        let persistedKey = "\(idempotencyPrefix).\(dedupeKey)"

        guard shouldCreateContact(profileId: payload.profileId, eventId: payload.eventId) else {
            print("[ContactSync] Skipped duplicate for event")
            return false
        }

        guard await requestAccessIfNeeded() else {
            lock.lock()
            inFlightKeys.remove(dedupeKey)
            lock.unlock()
            print("[ContactSync] Permission denied")
            return false
        }

        do {
            let newNote = buildNote(from: payload)
            let didSave = try await Task.detached(priority: .utility) { () throws -> Bool in
                let store = CNContactStore()
                let saveRequest = CNSaveRequest()

                let keys: [CNKeyDescriptor] = [
                    CNContactIdentifierKey as CNKeyDescriptor,
                    CNContactGivenNameKey as CNKeyDescriptor,
                    CNContactFamilyNameKey as CNKeyDescriptor,
                    CNContactPhoneNumbersKey as CNKeyDescriptor,
                    CNContactEmailAddressesKey as CNKeyDescriptor,
                    CNContactNoteKey as CNKeyDescriptor
                ]

                var existing: CNMutableContact?

                if let phone = payload.phoneNumber?.trimmingCharacters(in: .whitespacesAndNewlines), !phone.isEmpty {
                    let phonePredicate = CNContact.predicateForContacts(matching: CNPhoneNumber(stringValue: phone))
                    if let first = try store.unifiedContacts(matching: phonePredicate, keysToFetch: keys).first {
                        existing = first.mutableCopy() as? CNMutableContact
                    }
                }

                if existing == nil,
                   let email = payload.email?.trimmingCharacters(in: .whitespacesAndNewlines),
                   !email.isEmpty {
                    let emailPredicate = CNContact.predicateForContacts(matchingEmailAddress: email as NSString)
                    if let first = try store.unifiedContacts(matching: emailPredicate, keysToFetch: keys).first {
                        existing = first.mutableCopy() as? CNMutableContact
                    }
                }

                if let existing {
                    if existing.note.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                        existing.note = newNote
                    } else {
                        existing.note = existing.note + "\n\n---\n" + newNote
                    }
                    saveRequest.update(existing)
                    try store.execute(saveRequest)
                    print("[ContactSync] Updated existing contact")
                    return true
                }

                let newContact = CNMutableContact()
                let parts = payload.name
                    .split(separator: " ", omittingEmptySubsequences: true)
                    .map(String.init)

                if let first = parts.first {
                    newContact.givenName = first
                }
                if parts.count > 1 {
                    newContact.familyName = parts.dropFirst().joined(separator: " ")
                }
                if newContact.givenName.isEmpty {
                    newContact.givenName = payload.name
                }

                if let phone = payload.phoneNumber?.trimmingCharacters(in: .whitespacesAndNewlines), !phone.isEmpty {
                    let labeled = CNLabeledValue(label: CNLabelPhoneNumberMobile, value: CNPhoneNumber(stringValue: phone))
                    newContact.phoneNumbers = [labeled]
                }

                if let email = payload.email?.trimmingCharacters(in: .whitespacesAndNewlines), !email.isEmpty {
                    let labeled = CNLabeledValue(label: CNLabelWork, value: email as NSString)
                    newContact.emailAddresses = [labeled]
                }

                newContact.note = newNote

                let containerId = store.defaultContainerIdentifier()
                saveRequest.add(newContact, toContainerWithIdentifier: containerId)
                try store.execute(saveRequest)
                print("[ContactSync] Created contact for \(payload.name)")
                return true
            }.value

            if didSave {
                lock.lock()
                defaults.set(true, forKey: persistedKey)
                inFlightKeys.remove(dedupeKey)
                lock.unlock()
                return true
            }

            lock.lock()
            inFlightKeys.remove(dedupeKey)
            lock.unlock()
            return false
        } catch {
            lock.lock()
            inFlightKeys.remove(dedupeKey)
            lock.unlock()
            print("[ContactSync] Save failed: \(error.localizedDescription)")
            return false
        }
    }
}
